name: ðŸ“¨ Deploy staff

on:
  push:
    branches: ["main"]
    paths:
      - staff/**
  pull_request:
    paths:
      - staff/**

jobs:
  deploy_staff:
    name: ðŸ“¨ Deploy staff
    uses: ./.github/workflows/cd.yml
    with:
      app_name: staff
